const pokeSprite = {
castform_sunny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10013.png",
espeon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png",
altaria: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/334.png",
duskull: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/355.png",
mismagius: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/429.png",
snorunt: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/361.png",
lotad: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/270.png",
pelipper: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/279.png",
golduck: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png",
froslass: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/478.png",
glalie: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/362.png",
ludicolo: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/272.png",
kingdra: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/230.png",
kyogre: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/382.png",
weavile: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/461.png",
beartic: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/614.png",
cubchoo: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/613.png",
glaceon: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/471.png",
piloswine: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/221.png",
kyurem: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/646.png",
ducklett: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/580.png",
mantyke: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/458.png",
gyarados: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
vanilluxe: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/584.png",
abomasnow: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/460.png",
zapdos: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
thundurus: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/642.png",
zekrom: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/644.png",

}
export default pokeSprite