import Head from "next/head";
import Header from "../components/Header.jsx"
import WeatherCard from "@/components/WeatherCard.jsx";
import WeatherPage from "./WeatherPage.jsx";
import React from "react";
import { useState } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Jersey+10&display=swap" rel="stylesheet"/>
      </Head>
      <main>
        <Header/>
        <WeatherPage/>
        {/* <WeatherCard props={{lat:43, lon:-81}}/> */}
      </main>
    </>
  );
}
